const express = require("express");
const { requireAuth } = require("../middleware/auth");
const { handleMessage, handleMessageStream } = require("../lib/chatbot");
const ollama = require("../lib/ollama");

const router = express.Router();

// In-memory conversation store keyed by user ID. In production you'd use
// Redis or a DB table, but for the prototype this is fine -- conversations
// reset on server restart, which is acceptable for a dev tool.
const conversations = new Map();
const MAX_HISTORY = 20; // keep last N messages per user to avoid prompt bloat

function getHistory(userId) {
  if (!conversations.has(userId)) {
    conversations.set(userId, []);
  }
  return conversations.get(userId);
}

function addToHistory(userId, role, text) {
  const history = getHistory(userId);
  history.push({ role, text });
  // Trim to prevent unbounded growth
  if (history.length > MAX_HISTORY) {
    history.splice(0, history.length - MAX_HISTORY);
  }
}

// ── POST /api/chat -- standard request/response ────────────────────────
router.post("/", requireAuth, async (req, res) => {
  const { message } = req.body;
  if (!message || typeof message !== "string") {
    return res.status(400).json({ error: "message is required." });
  }
  try {
    const history = getHistory(req.user.id);
    const reply = await handleMessage(message, req.user, history);

    // Persist both sides of the conversation
    addToHistory(req.user.id, "user", message);
    addToHistory(req.user.id, "bot", reply);

    res.json({ reply });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Could not process that message." });
  }
});

// ── GET /api/chat/stream?message=... -- Server-Sent Events ─────────────
// Streams tokens as they're generated by the LLM so the frontend can
// render them incrementally (ChatGPT-style typing effect).
router.get("/stream", requireAuth, async (req, res) => {
  const message = req.query.message;
  if (!message) {
    return res.status(400).json({ error: "message query param is required." });
  }

  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.flushHeaders();

  const history = getHistory(req.user.id);
  addToHistory(req.user.id, "user", message);

  let fullReply = "";

  try {
    await handleMessageStream(message, req.user, history, (chunk, done) => {
      fullReply += chunk;
      res.write(`data: ${JSON.stringify({ chunk, done })}\n\n`);
      if (done) {
        addToHistory(req.user.id, "bot", fullReply);
        res.write("data: [DONE]\n\n");
        res.end();
      }
    });
  } catch (err) {
    console.error(err);
    res.write(`data: ${JSON.stringify({ error: "Stream failed", done: true })}\n\n`);
    res.end();
  }
});

// ── DELETE /api/chat/history -- clear conversation ─────────────────────
router.delete("/history", requireAuth, (req, res) => {
  conversations.delete(req.user.id);
  res.json({ cleared: true });
});

// ── GET /api/chat/status -- Ollama health + model info ─────────────────
router.get("/status", requireAuth, async (req, res) => {
  const available = await ollama.isAvailable();
  res.json({
    ollamaAvailable: available,
    model: process.env.OLLAMA_MODEL || "gpt oss 20b",
    mode: available ? "ai" : "rule-based",
    features: available
      ? [
          "Multi-turn conversations",
          "Road condition analysis",
          "Repair recommendations",
          "Executive summaries",
          "Complaint analysis",
          "Degradation forecasting",
          "Natural language queries",
        ]
      : ["Rule-based FAQ", "Dashboard stats", "Road lookups"],
  });
});

// ── POST /api/chat/analyze-road -- dedicated road analysis ─────────────
router.post("/analyze-road", requireAuth, async (req, res) => {
  const { roadName } = req.body;
  if (!roadName) {
    return res.status(400).json({ error: "roadName is required." });
  }
  try {
    const reply = await handleMessage(`analyze ${roadName}`, req.user, []);
    res.json({ analysis: reply });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Analysis failed." });
  }
});

// ── POST /api/chat/repair-advice -- dedicated repair recommendations ───
router.post("/repair-advice", requireAuth, async (req, res) => {
  const { roadName } = req.body;
  if (!roadName) {
    return res.status(400).json({ error: "roadName is required." });
  }
  try {
    const reply = await handleMessage(`repair ${roadName}`, req.user, []);
    res.json({ advice: reply });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Repair advice generation failed." });
  }
});

// ── POST /api/chat/summarize -- AI summary of arbitrary data ───────────
router.post("/summarize", requireAuth, async (req, res) => {
  const { prompt } = req.body;
  if (!prompt) {
    return res.status(400).json({ error: "prompt is required." });
  }
  try {
    const summary = await ollama.generate(
      `${ollama.SYSTEM_PROMPT}\n\n${prompt}`,
      { maxTokens: 512 }
    );
    res.json({ summary: summary || "AI summarization is currently unavailable." });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Summarization failed." });
  }
});

module.exports = router;
